name: Build and release geth-rrr image -x
env:
  DOCKERHUB_USERNAME: robinbryce
  QUORUM_VERSION: v21.10.0
  # The quorum fork repo should be tagged before releasing go-rrr with the
  # expected final release tag. Eg v0.2.0. Then do as many v0.2.0-aN tags as
  # you need to finalise the release before ultimately doing the v0.2.0. If
  # that final release fails for an intermitent reason that requires a fixup,
  # force retag the fixup or start again with a new tag
  QUORUM_RRR_VERSION: ${{ GITHUB_REF }}
on:
  workflow_dispatch: []
  release:
    types: [published, prerelease]

jobs:
  build-and-release-images:
    name: Build and publish geth-rrr image
    runs-on: ubuntu-latest
    steps:

      -
        name: finalise env
        run: |
          echo "QUORUM_RRR_VERSION=$(echo ${QUORUM_RRR_VERSION%-*}" >> $GITHUB_ENV
          echo QUORUM_RRR_VERSION=$QUORUM_RRR_VERSION

      -
        name: checkout go-rrr
        uses: actions/checkout@v2
        with:
          path: go-rrr
          token: ${{ github.token }}

      -
        name: checkout quorum
        uses: actions/checkout@v2
        with:
          repository: RobustRoundRobin/quorum
          ref: "${{ env.QUORUM_VERSION }}-rrr_${{ env.QUORUM_RRR_VERSION }}"
          path: quorum
          token: ${{ github.token }}
      -
        name: copy buildcontext files
        run: |
          cp go-rrr/cicd/buildcontext/* $GITHUB_WORKSPACE/
      -
        name: Login to dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PUBLISH }}
      -
        name: Extract tags, labels for geth image
        id: geth-meta
        uses: docker/metadata-action@v3
        with:
          images: robustroundrobin/geth
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
      -
        name: Build and push geth
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.geth-meta.outputs.tags }}
          labels: ${{ steps.geth-meta.outputs.labels }}
      -
        name: Extract tags, labels for rrrctl image
        id: rrrctl-meta
        uses: docker/metadata-action@v3
        with:
          images: robustroundrobin/rrrctl
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-

      -
        name: Build and push rrrctl
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-rrrctl
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.rrrctl-meta.outputs.tags }}
          labels: ${{ steps.rrrctl-meta.outputs.labels }}
