name: "smoketest (rrr, raft and ibft consensus in forked go-quorum)"
on:
  workflow_dispatch:
    inputs:

      namespaceprefix:
        description: 'prefix to the namespace for all workloads'
        type: string
        default: "go-rrr-smoketest-"

      maxwait:
        description: >
          maximum number of seconds (total) to wait for any intermediate result, eg deployment or
          loadtesting
        type: string
        default: "360"

  release:
    types: [published, prerelease]

jobs:
  raft:
    uses: robinbryce/benchblock/.github/workflows/loadtest-on-gcp.yaml@main
    with:
      project_id: "fetlar-1"
      location: "europe-west2-a"
      cluster_name: "kluster"
      consensus: raft
      numnodes: 3
      namespaceprefix: ${{ github.event.inputs.namespaceprefix }}
      maxwait: ${{ inputs.maxwait }}

    secrets:
      gcp_project_key: ${{ secrets.GCP_PROJECT_KEY_FETLAR }}

  ibft:
    uses: robinbryce/benchblock/.github/workflows/loadtest-on-gcp.yaml@main
    with:
      project_id: "fetlar-1"
      location: "europe-west2-a"
      cluster_name: "kluster"
      consensus: "ibft"
      numnodes: 5
      profile: ${{ github.event.inputs.profile }}
      namespaceprefix: ${{ github.event.inputs.namespaceprefix }}
      maxwait: ${{ inputs.maxwait }}

    secrets:
      gcp_project_key: ${{ secrets.GCP_PROJECT_KEY_FETLAR }}

  rrr:
    uses: robinbryce/benchblock/.github/workflows/loadtest-on-gcp.yaml@main
    with:
      project_id: "fetlar-1"
      location: "europe-west2-a"
      cluster_name: "kluster"
      consensus: "rrr"
      numnodes: 9
      profile: ${{ github.event.inputs.profile }}
      namespaceprefix: ${{ github.event.inputs.namespaceprefix }}
      maxwait: ${{ inputs.maxwait }}

    secrets:
      gcp_project_key: ${{ secrets.GCP_PROJECT_KEY_FETLAR }}
