name: "smoketest (rrr, raft and ibft consensus in forked go-quorum)"
env:
  MAXWAIT: "360"
  NAMESPACEPREFIX: "go-rrr-smoketest-"

on:
  workflow_dispatch:
  release:
    types: [published, prerelease]

jobs:
  raft:
    uses: robinbryce/benchblock/.github/workflows/loadtest-on-gcp.yaml@main
    with:
      project_id: "fetlar-1"
      location: "europe-west2-a"
      cluster_name: "kluster"
      consensus: raft
      numnodes: 3
      namespaceprefix: ${{ env.NAMESPACEPREFIX }}
      maxwait: ${{ env.MAXWAIT }}

    secrets:
      gcp_project_key: ${{ secrets.GCP_PROJECT_KEY_FETLAR }}

  ibft:
    uses: robinbryce/benchblock/.github/workflows/loadtest-on-gcp.yaml@main
    with:
      project_id: "fetlar-1"
      location: "europe-west2-a"
      cluster_name: "kluster"
      consensus: "ibft"
      numnodes: 5
      profile: ${{ github.event.inputs.profile }}
      namespaceprefix: ${{ env.NAMESPACEPREFIX }}
      maxwait: ${{ env.MAXWAIT }}

    secrets:
      gcp_project_key: ${{ secrets.GCP_PROJECT_KEY_FETLAR }}

  rrr:
    uses: robinbryce/benchblock/.github/workflows/loadtest-on-gcp.yaml@main
    with:
      project_id: "fetlar-1"
      location: "europe-west2-a"
      cluster_name: "kluster"
      consensus: "rrr"
      numnodes: 9
      profile: ${{ github.event.inputs.profile }}
      namespaceprefix: ${{ env.NAMESPACEPREFIX }}
      maxwait: ${{ env.MAXWAIT }}

    secrets:
      gcp_project_key: ${{ secrets.GCP_PROJECT_KEY_FETLAR }}
